PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX OGI: <http://ogi.eu/#>
PREFIX OGI-Observations:  <http://ogi.eu/observations/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT{
		?observation a qb:observation;
				OGI:time ?time;
				OGI:longitude ?longitude;
				OGI:latitude ?latitude;
				OGI:significant_wave_height ?significant_wave_height;
				OGI:swell_wave_height ?swell_wave_height;
				OGI:mean_wave_direction ?mean_wave_direction;
				OGI:mean_wave_period ?mean_wave_period;
				.
	}
#FROM <file:/datasets/tarql/IWBNetwork_d6c4_456c_1d8d.csv>
WHERE {
BIND (uri(CONCAT('http://ogi.eu/observations/',StrUUID())) AS ?observation)
}

				
