
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX OGI: <http://ogi.eu/#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT{
		?observation a qb:observation;
				OGI:time ?time;
				OGI:station_id ?station_id;
				OGI:longitude ?longitude;
				OGI:latitude ?latitude;
				OGI:altitude ?altitude;
				OGI:water_Level ?Water_Level;
				OGI:water_Level_LAT ?Water_Level_LAT;
				OGI:water_Level_OD_Malin ?Water_Level_OD_Malin;
				OGI:qC_Flag ?QC_Flag;
				.
	}
#FROM <file:/home/mohade/datasets/tarql/IWBNetwork_d6c4_456c_1d8d.csv>
WHERE {
BIND (uri(CONCAT('http://ogi.eu/observations/',StrUUID())) AS ?observation)
}

				
