PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX OGI: <http://ogi.eu/#>
PREFIX OGI-Observations: <http://ogi.eu/observations/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT{
		?observation a qb:observation;
				OGI:time ?time;
				OGI:longitude ?longitude;
				OGI:latitude ?latitude;
				OGI:station_id ?station_id;
				OGI:peakPeriod ?PeakPeriod;
				OGI:peakDirection ?PeakDirection;
				OGI:upcrossPeriod ?UpcrossPeriod;
				OGI:significant_wave_height ?SignificantWaveHeight;
				OGI:seaTemperature ?SeaTemperature;
				OGI:hmax ?Hmax;
				OGI:tHmax ?THmax;
				OGI:meanCurDirTo ?MeanCurDirTo;
				OGI:meanCurSpeed ?MeanCurSpeed;
				OGI:significantWaveHeight_qc ?SignificantWaveHeight_qc;
				OGI:peakPeriod_qc ?PeakPeriod_qc;
				OGI:peakDirection_qc ?PeakDirection_qc;
				OGI:upcrossPeriod_qc ?UpcrossPeriod_qc;
				OGI:seaTemperature_qc ?SeaTemperature_qc;
				OGI:hmax_qc ?Hmax_qc;
				OGI:tHmax_qc ?THmax_qc;
				OGI:meanCurDirTo_qc ?MeanCurDirTo_qc;
				OGI:meanCurSpeed_qc ?MeanCurSpeed_qc;
				
				.
	}
#FROM <file:/datasets/tarql/IWBNetwork_d6c4_456c_1d8d.csv>
WHERE {
BIND (uri(CONCAT('http://ogi.eu/observations/',StrUUID())) AS ?observation)
}

				
